[versions]
agp = "9.0.0"
android-junit5 = "2.0.1"
androidx-activity = "1.12.4"
androidx-constraintlayout = "1.1.1"
androidx-lifecycle = "2.10.0"
androidx-navigation = "2.9.7"
androidx-test-espresso = "3.7.0"
androidx-test-ext = "1.3.0"
appcompat = "1.7.1"
coil = "2.7.0"
kotlin = "2.3.10"
core-ktx = "1.17.0"
junit = "4.13.2"
jupiter-junit = "6.0.2"
kotlinx-coroutines-test = "1.10.2"
ksp = "2.3.2"
material = "1.13.0"
room-version = "2.8.4"
runner = "1.7.0"
firebase-perf-ktx = "21.0.5"
firebase-abt = "23.0.1"
lottie = "6.7.1"
firebase-common-ktx = "21.0.0"
lifecycle-process = "2.10.0"
core = "1.17.0"
javapoet = "1.13.0"
animation = "1.10.3"
compose-material-core = "1.5.6"

[libraries]
#Compose
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = "androidx.compose:compose-bom:2026.02.00"
compose-constraints = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
compose-material3 = "androidx.compose.material3:material3:1.4.0"
compose-material_icons_extends = "androidx.compose.material:material-icons-extended:1.7.8"
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
datastore = "androidx.datastore:datastore-preferences:1.2.0"
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "34.9.0" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
hilt-android = { module = "com.google.dagger:hilt-android", version = "2.59.1" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version = "2.59.1" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version = "2.59.1" }
hilt-navigation = "androidx.hilt:hilt-navigation-compose:1.3.0"
junit = { module = "junit:junit", version.ref = "junit" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter-junit" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-junit" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter-junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
lifecycle-compose-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
lifecycle-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = "io.mockk:mockk:1.14.9"
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-version" }
splashscreen = "androidx.core:core-splashscreen:1.2.0"
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
timber = "com.jakewharton.timber:timber:5.0.1"
turbine = "app.cash.turbine:turbine:1.2.1"
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx", version.ref = "firebase-perf-ktx" }
firebase-abt = { group = "com.google.firebase", name = "firebase-abt", version.ref = "firebase-abt" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebase-common-ktx" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-process" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
androidx-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
androidx-compose-material-core = { group = "androidx.wear.compose", name = "compose-material-core", version.ref = "compose-material-core" }

[bundles]
compose = [
    "activity-compose",
    "coil",
    "compose-constraints",
    "compose-material3",
    "compose-material_icons_extends",
    "compose-navigation",
    "compose-preview",
    "compose-ui",
    "compose-ui-graphics",
    "lifecycle-compose-runtime",
    "lifecycle-compose-viewmodel",
    "lottie-compose",
]
firebase = [
    "firebase-auth",
    "firebase-crashlytics",
    "firebase-database",
    "firebase-firestore",
    "firebase-storage",
]
jupiter = [
    "jupiter-api",
    "jupiter-params",
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidJUnit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version = "2.8.4" }
ben-manes-versions = "com.github.ben-manes.versions:0.53.0"
kotlin-android = "org.jetbrains.kotlin.android:2.3.10"
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version = "2.59.1" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
